/*
 * Copyright (c) 2008-2016 Computer Network Information Center (CNIC), Chinese Academy of Sciences.
 * 
 * This file is part of Duckling project.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 *
 */
package com.outsideinsdk;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 * This class is a wrapper for a return code generated by the native process of an <code>Export</code> object.
 * Instances of this class are immutable and, once obtained, can be queried for the integer value of the code
 * they represent, or for the <code>String</code> text of that code.  The text is localized, and queries will
 * return text based on a provided locale.  If no locale is provided, the default locale will be used.
 *
 * @author John Pazdernik
 * @version 1.00
 * @see <a href=http://www.java.sun.com/j2se/1.3/docs/api/java/util/Locale.html>java.util.Locale</a>
 */
public class ExportStatusCode {

	public static final ExportStatusCode SCCERR_OK = new ExportStatusCode( 0 );
	public static final ExportStatusCode SCCERR_UNKNOWN = new ExportStatusCode( 18 );
	public static final ExportStatusCode SCCERR_LEG_UNKNOWNFAILURE = new ExportStatusCode( 8 );
	public static final ExportStatusCode SCCERR_BADPARAM = new ExportStatusCode( 15 );
	public static final ExportStatusCode SCCERR_ABORT = new ExportStatusCode( 32 );
	public static final ExportStatusCode SCCERR_CANCEL = new ExportStatusCode( 20 );
	public static final ExportStatusCode SCCERR_NOINIT = new ExportStatusCode( 21 );
	public static final ExportStatusCode SCCERR_MACINITFAILED = new ExportStatusCode( 28 );
	public static final ExportStatusCode SCCERR_MESSAGEHANDLED = new ExportStatusCode( 24 );
	public static final ExportStatusCode SCCERR_NOITEM = new ExportStatusCode( 37 );
	public static final ExportStatusCode SCCERR_NONEFOUND = new ExportStatusCode( 25 );
	public static final ExportStatusCode SCCERR_MORE = new ExportStatusCode( 35 );
	public static final ExportStatusCode SCCERR_NOTHANDLED = new ExportStatusCode( 50 );
	public static final ExportStatusCode SCCERR_NODATATORENDER = new ExportStatusCode( 51 );
	public static final ExportStatusCode SCCERR_SYSTEM = new ExportStatusCode( 0x80 );
	public static final ExportStatusCode SCCERR_PROCCREATE = new ExportStatusCode( 0x81 );
	public static final ExportStatusCode SCCERR_PROCDESTROY = new ExportStatusCode( 0x82 );
	public static final ExportStatusCode SCCERR_PROCTIMEOUT = new ExportStatusCode( 0x83 );
	public static final ExportStatusCode SCCERR_ASSERTIONFAILED = new ExportStatusCode( 0x84 );
	public static final ExportStatusCode SCCERR_DEBUGERROR = new ExportStatusCode( 0x85 );
	public static final ExportStatusCode SCCERR_NOCHANGE = new ExportStatusCode( 0x86 );
	public static final ExportStatusCode SCCERR_DISPLAYOPENFAILED = new ExportStatusCode( 0x87 );
	public static final ExportStatusCode SCCERR_WRONGDATAFORMAT = new ExportStatusCode( 0x88 );
	public static final ExportStatusCode SCCERR_UNKNOWNERRORCODE = new ExportStatusCode( 0xff );

	public static final ExportStatusCode SCCERR_ALLOCFAILED = new ExportStatusCode( 13 );
	public static final ExportStatusCode SCCERR_OUTOFMEMORY = new ExportStatusCode( 30 );
	public static final ExportStatusCode SCCERR_INSUFFICIENTBUFFER = new ExportStatusCode( 46 );
	public static final ExportStatusCode SCCERR_MEMORYLEAK = new ExportStatusCode( 48 );
	public static final ExportStatusCode SCCERR_MEMTABLEFULL = new ExportStatusCode( 0x100 );
	public static final ExportStatusCode SCCERR_INVALIDHANDLE = new ExportStatusCode( 0x101 );
	public static final ExportStatusCode SCCERR_NULLHANDLE = new ExportStatusCode( 0x102 );
	public static final ExportStatusCode SCCERR_LOCKEDHANDLE = new ExportStatusCode( 0x103 );
	public static final ExportStatusCode SCCERR_UNLOCKEDHANDLE = new ExportStatusCode( 0x104 );

	public static final ExportStatusCode SCCERR_NOFILE = new ExportStatusCode( 16 );
	public static final ExportStatusCode SCCERR_FILEOPENFAILED = new ExportStatusCode( 7 );
	public static final ExportStatusCode SCCERR_SUPFILEOPENFAILED = new ExportStatusCode( 12 );
	public static final ExportStatusCode SCCERR_BADFILE = new ExportStatusCode( 9 );
	public static final ExportStatusCode SCCERR_EMPTYFILE = new ExportStatusCode( 10 );
	public static final ExportStatusCode SCCERR_PROTECTEDFILE = new ExportStatusCode( 11 );
	public static final ExportStatusCode SCCERR_FILECREATE = new ExportStatusCode( 34 );
	public static final ExportStatusCode SCCERR_FILECHANGED = new ExportStatusCode( 38 );
	public static final ExportStatusCode SCCERR_FILEWRITEFAILED = new ExportStatusCode( 47 );
	public static final ExportStatusCode SCCERR_EOF = new ExportStatusCode( 31 );
	public static final ExportStatusCode SCCERR_INVALIDFILEHANDLE = new ExportStatusCode( 0x140 );
	public static final ExportStatusCode SCCERR_OPENINPUTFAILED = new ExportStatusCode( 0x141 );
	public static final ExportStatusCode SCCERR_FILECOPYFAILED = new ExportStatusCode( 0x142 );
	public static final ExportStatusCode SCCERR_FILENOTAVAILABLE = new ExportStatusCode( 0x143 );
	public static final ExportStatusCode SCCERR_RECORDDELETED = new ExportStatusCode( 0x144 );
	public static final ExportStatusCode SCCERR_INVALIDPATH = new ExportStatusCode( 0x145 );
	public static final ExportStatusCode SCCERR_INVALIDSPEC = new ExportStatusCode( 0x146 );
	
	public static final ExportStatusCode SCCERR_EMPTYCODE = new ExportStatusCode( 0x8b );

	public static final ExportStatusCode SCCERR_INVALIDID = new ExportStatusCode( 1 );
	public static final ExportStatusCode SCCERR_UNSUPPORTEDFORMAT = new ExportStatusCode( 14 );

	public static final ExportStatusCode SCCERR_NOFILTER = new ExportStatusCode( 4 );
	public static final ExportStatusCode SCCERR_FILTERLOADFAILED = new ExportStatusCode( 2 );
	public static final ExportStatusCode SCCERR_FILTERALLOCFAILED = new ExportStatusCode( 3 );
	public static final ExportStatusCode SCCERR_FILTERTIMEOUT = new ExportStatusCode( 27 );
	public static final ExportStatusCode SCCERR_FILTEREXCEPTACCESS = new ExportStatusCode( 39 );
	public static final ExportStatusCode SCCERR_FILTEREXCEPTZERO = new ExportStatusCode( 40 );
	public static final ExportStatusCode SCCERR_FILTEREXCEPTOTHER = new ExportStatusCode( 41 );
	public static final ExportStatusCode SCCERR_FILTERSCRAMBLEERROR = new ExportStatusCode( 42 );
	public static final ExportStatusCode SCCERR_FILTERTILEMAXEXCEEDED = new ExportStatusCode( 43 );

	public static final ExportStatusCode SCCERR_NODISPLAYENGINE = new ExportStatusCode( 19 );
	public static final ExportStatusCode SCCERR_DISPLAYINITFAILED = new ExportStatusCode( 5 );

	public static final ExportStatusCode SCCERR_CHUNKERINITFAILED = new ExportStatusCode( 6 );
	public static final ExportStatusCode SCCERR_DATANOTAVAILABLE = new ExportStatusCode( 45 );

	public static final ExportStatusCode SCCERR_VIEWERBAIL = new ExportStatusCode( 36 );

	public static final ExportStatusCode SCCERR_CHARMAPFAILED = new ExportStatusCode( 33 );

	public static final ExportStatusCode SCCERR_LASTPAGE = new ExportStatusCode( 22 );
	public static final ExportStatusCode SCCERR_NOPAGE = new ExportStatusCode( 23 );
	public static final ExportStatusCode SCCERR_OTHERPRINTING = new ExportStatusCode( 29 );

	public static final ExportStatusCode SCCERR_FEATURENOTAVAIL = new ExportStatusCode( 17 );
	public static final ExportStatusCode SCCERR_RAWTEXTDISABLED = new ExportStatusCode( 26 );

	public static final ExportStatusCode SCCERR_DATAREMOTEERROR = new ExportStatusCode( 44 );

	public static final ExportStatusCode SCCERR_EXCEPTION = new ExportStatusCode( 0x3c0 );
	public static final ExportStatusCode SCCERR_EXCEPT_ACCESS_VIOLATION = new ExportStatusCode( 0x3c1 );
	public static final ExportStatusCode SCCERR_EXCEPT_BREAKPOINT = new ExportStatusCode( 0x3c2 );
	public static final ExportStatusCode SCCERR_EXCEPT_DATATYPE_MISALIGNMENT = new ExportStatusCode( 0x3c3 );
	public static final ExportStatusCode SCCERR_EXCEPT_SINGLE_STEP = new ExportStatusCode( 0x3c4 );
	public static final ExportStatusCode SCCERR_EXCEPT_ARRAY_BOUNDS_EXCEEDED = new ExportStatusCode( 0x3c5 );
	public static final ExportStatusCode SCCERR_EXCEPT_FLT_DENORMAL_OPERAND = new ExportStatusCode( 0x3c6 );
	public static final ExportStatusCode SCCERR_EXCEPT_FLT_DIVIDE_BY_ZERO = new ExportStatusCode( 0x3c7 );
	public static final ExportStatusCode SCCERR_EXCEPT_FLT_INEXACT_RESULT = new ExportStatusCode( 0x3c8 );
	public static final ExportStatusCode SCCERR_EXCEPT_FLT_INVALID_OPERATION = new ExportStatusCode( 0x3c9 );
	public static final ExportStatusCode SCCERR_EXCEPT_FLT_OVERFLOW = new ExportStatusCode( 0x3ca );
	public static final ExportStatusCode SCCERR_EXCEPT_FLT_STACK_CHECK = new ExportStatusCode( 0x3cb );
	public static final ExportStatusCode SCCERR_EXCEPT_FLT_UNDERFLOW = new ExportStatusCode( 0x3cc );
	public static final ExportStatusCode SCCERR_EXCEPT_INT_DIVIDE_BY_ZERO = new ExportStatusCode( 0x3cd );
	public static final ExportStatusCode SCCERR_EXCEPT_INT_OVERFLOW = new ExportStatusCode( 0x3ce );
	public static final ExportStatusCode SCCERR_EXCEPT_PRIV_INSTRUCTION = new ExportStatusCode( 0x3cf );
	public static final ExportStatusCode SCCERR_EXCEPT_NONCONTINUABLE = new ExportStatusCode( 0x3d0 );
	public static final ExportStatusCode SCCERR_EXCEPT_UNKNOWN = new ExportStatusCode( 0x3d1 );

	public static final ExportStatusCode SCCERR_TESTNOTAVAILABLE = new ExportStatusCode( 0x400 );
	public static final ExportStatusCode SCCERR_TESTTIMEOUT = new ExportStatusCode( 0x401 );
	public static final ExportStatusCode SCCERR_CREATEBINFAILED = new ExportStatusCode( 0x402 );
	public static final ExportStatusCode SCCERR_OPENBINFAILED = new ExportStatusCode( 0x403 );
	public static final ExportStatusCode SCCERR_WRITEBINFAILED = new ExportStatusCode( 0x404 );
	public static final ExportStatusCode SCCERR_READBINFAILED = new ExportStatusCode( 0x405 );
	public static final ExportStatusCode SCCERR_OPENDUMPFAILED = new ExportStatusCode( 0x406 );
	public static final ExportStatusCode SCCERR_COMPAREFAILED = new ExportStatusCode( 0x407 );
	public static final ExportStatusCode SCCERR_CHUNKERRUNMISMATCH = new ExportStatusCode( 0x408 );
	public static final ExportStatusCode SCCERR_CHUNKERSIZEMISMATCH = new ExportStatusCode( 0x409 );
	public static final ExportStatusCode SCCERR_CHUNKERFAILED = new ExportStatusCode( 0x40a );
	public static final ExportStatusCode SCCERR_CHUNKEROVERRUN = new ExportStatusCode( 0x40b );
	public static final ExportStatusCode SCCERR_COMPRESSIONFAILED = new ExportStatusCode( 0x40c );
	public static final ExportStatusCode SCCERR_STREAMBAIL = new ExportStatusCode( 0x40d );
	public static final ExportStatusCode SCCERR_MISSINGELEMENT = new ExportStatusCode( 0x40e );
	public static final ExportStatusCode SCCERR_TESTCOMPLETE = new ExportStatusCode( 0x40f );
	public static final ExportStatusCode SCCERR_TESTMODESWITCH = new ExportStatusCode( 0x410 );
	public static final ExportStatusCode SCCERR_BASELINEFILENOTFOUND = new ExportStatusCode( 0x411 );
	public static final ExportStatusCode SCCERR_COMPAREFILENOTFOUND = new ExportStatusCode( 0x412 );
	public static final ExportStatusCode SCCERR_TECHNOTAVAILABLE = new ExportStatusCode( 0x420 );
	public static final ExportStatusCode SCCERR_TESTFILESEMPTY = new ExportStatusCode( 0x421 );

	public static final ExportStatusCode SCCERR_INVALIDRESPONSE = new ExportStatusCode( 0x500 );
	public static final ExportStatusCode SCCERR_COMMTIMEOUT = new ExportStatusCode( 0x501 );
	public static final ExportStatusCode SCCERR_COMMUNKNOWN = new ExportStatusCode( 0x502 );
	public static final ExportStatusCode SCCERR_CONNECTIONREFUSED = new ExportStatusCode( 0x503 );
	public static final ExportStatusCode SCCERR_COMMFAULT = new ExportStatusCode( 0x504 );
	public static final ExportStatusCode SCCERR_CONNECTIONDOWN = new ExportStatusCode( 0x505 );
	public static final ExportStatusCode SCCERR_CONNECTIONUNREACHABLE = new ExportStatusCode( 0x506 );
	public static final ExportStatusCode SCCERR_DISCONNECTED = new ExportStatusCode( 0x507 );
	public static final ExportStatusCode SCCERR_SYNCHRONIZE = new ExportStatusCode( 0x508 );

	public static final ExportStatusCode SCCERR_BI_FIRSTERROR = new ExportStatusCode( 0x600 );
	public static final ExportStatusCode SCCERR_BI_GENERAL = new ExportStatusCode( 0x600 );
	public static final ExportStatusCode SCCERR_BI_TREE = new ExportStatusCode( 0x601 );
	public static final ExportStatusCode SCCERR_BI_INVALID_VAL = new ExportStatusCode( 0x602 );
	public static final ExportStatusCode SCCERR_BI_NONE = new ExportStatusCode( 0x603 );
	public static final ExportStatusCode SCCERR_BI_ENDMACRO = new ExportStatusCode( 0x604 );
	public static final ExportStatusCode SCCERR_BI_ENDBARNEY = new ExportStatusCode( 0x604 );
	public static final ExportStatusCode SCCERR_BI_START = new ExportStatusCode( 0x605 );
	public static final ExportStatusCode SCCERR_BI_LT = new ExportStatusCode( 0x605 );
	public static final ExportStatusCode SCCERR_BI_EQ = new ExportStatusCode( 0x606 );
	public static final ExportStatusCode SCCERR_BI_END = new ExportStatusCode( 0x607 );
	public static final ExportStatusCode SCCERR_BI_GT = new ExportStatusCode( 0x607 );
	public static final ExportStatusCode SCCERR_BI_ACTION = new ExportStatusCode( 0x608 );
	public static final ExportStatusCode SCCERR_BI_SECTION = new ExportStatusCode( 0x609 );
	public static final ExportStatusCode SCCERR_BI_BARNEY = new ExportStatusCode( 0x609 );
	public static final ExportStatusCode SCCERR_BI_ELEMENT = new ExportStatusCode( 0x60a );
	public static final ExportStatusCode SCCERR_BI_LINK = new ExportStatusCode( 0x60b );
	public static final ExportStatusCode SCCERR_BI_TAG = new ExportStatusCode( 0x60c );
	public static final ExportStatusCode SCCERR_BI_TEMPLATE = new ExportStatusCode( 0x60d );
	public static final ExportStatusCode SCCERR_BI_TYPE = new ExportStatusCode( 0x60e );
	public static final ExportStatusCode SCCERR_BI_TYPENAME = new ExportStatusCode( 0x60f );
	public static final ExportStatusCode SCCERR_BI_DEFINE = new ExportStatusCode( 0x610 );
	public static final ExportStatusCode SCCERR_BI_DOCUMENT = new ExportStatusCode( 0x611 );
	public static final ExportStatusCode SCCERR_BI_GENLINK = new ExportStatusCode( 0x612 );
	public static final ExportStatusCode SCCERR_BI_INSERT = new ExportStatusCode( 0x613 );
	public static final ExportStatusCode SCCERR_BI_REPEAT = new ExportStatusCode( 0x614 );
	public static final ExportStatusCode SCCERR_BI_CHKTRAN = new ExportStatusCode( 0x615 );
	public static final ExportStatusCode SCCERR_BI_ALLOC = new ExportStatusCode( 0x616 );
	public static final ExportStatusCode SCCERR_BI_INVALIDCMD = new ExportStatusCode( 0x617 );
	public static final ExportStatusCode SCCERR_BI_INVALIDERRNUM = new ExportStatusCode( 0x618 );
	public static final ExportStatusCode SCCERR_BI_HANDLEELEM = new ExportStatusCode( 0x619 );
	public static final ExportStatusCode SCCERR_BI_ASISOUTTEXT = new ExportStatusCode( 0x61a );
	public static final ExportStatusCode SCCERR_BI_OUTTEXT = new ExportStatusCode( 0x61b );
	public static final ExportStatusCode SCCERR_BI_NOTEMPLATE = new ExportStatusCode( 0x61c );
	public static final ExportStatusCode SCCERR_BI_OUTFILEFAIL = new ExportStatusCode( 0x61d );
	public static final ExportStatusCode SCCERR_NOENDREPEAT = new ExportStatusCode( 0x61e );
	public static final ExportStatusCode SCCERR_NOENDIF = new ExportStatusCode( 0x61f );
	public static final ExportStatusCode SCCERR_NOENDIGNORE = new ExportStatusCode( 0x620 );
	public static final ExportStatusCode SCCERR_NONREPEAT = new ExportStatusCode( 0x621 );
	public static final ExportStatusCode SCCERR_REPEATENDONINDEX = new ExportStatusCode( 0x622 );
	public static final ExportStatusCode SCCERR_IFENDONINDEX = new ExportStatusCode( 0x623 );
	public static final ExportStatusCode SCCERR_INSERTENDONINDEX = new ExportStatusCode( 0x624 );
	public static final ExportStatusCode SCCERR_NOELEMENT = new ExportStatusCode( 0x625 );
	public static final ExportStatusCode SCCERR_INVALIDTAG = new ExportStatusCode( 0x626 );
	public static final ExportStatusCode SCCERR_NOSTARTTAG = new ExportStatusCode( 0x627 );
	public static final ExportStatusCode SCCERR_INVALIDTYPE = new ExportStatusCode( 0x628 );
	public static final ExportStatusCode SCCERR_NOVALUE = new ExportStatusCode( 0x629 );
	public static final ExportStatusCode SCCERR_NOCONDITION = new ExportStatusCode( 0x62a );
	public static final ExportStatusCode SCCERR_INVALIDLINKPARAM = new ExportStatusCode( 0x62b );
	public static final ExportStatusCode SCCERR_NOLINKPARAM = new ExportStatusCode( 0x62c );
	public static final ExportStatusCode SCCERR_BADCOUNTORVALUE = new ExportStatusCode( 0x62d );
	public static final ExportStatusCode SCCERR_INVALIDELSE = new ExportStatusCode( 0x62e );
	public static final ExportStatusCode SCCERR_INVALIDCOND = new ExportStatusCode( 0x62f );
	public static final ExportStatusCode SCCERR_TEMPLATECREATE = new ExportStatusCode( 0x630 );
	public static final ExportStatusCode SCCERR_MAXELEMSPASSED = new ExportStatusCode( 0x631 );
	public static final ExportStatusCode SCCERR_NOTYPE = new ExportStatusCode( 0x632 );
	public static final ExportStatusCode SCCERR_CUSTOMELEMENT = new ExportStatusCode( 0x633 );
	public static final ExportStatusCode SCCERR_INVALIDELSEIF = new ExportStatusCode( 0x634 );
	public static final ExportStatusCode SCCERR_BI_CSSPRAGMA = new ExportStatusCode( 0x635 );
	public static final ExportStatusCode SCCERR_BI_ANCHOR = new ExportStatusCode( 0x636 );
	public static final ExportStatusCode SCCERR_BI_LABEL = new ExportStatusCode( 0x637 );
	public static final ExportStatusCode SCCERR_BI_DECKSIZEEXCEEDED = new ExportStatusCode( 0x638 );
	public static final ExportStatusCode SCCERR_BI_UNSUPPORTEDMACRO = new ExportStatusCode( 0x639 );
	public static final ExportStatusCode SCCERR_INTERNALEXPORTFILTER = new ExportStatusCode( 0x63A );
	public static final ExportStatusCode SCCERR_TEMPLATEPARSE = new ExportStatusCode( 0x63B );
	public static final ExportStatusCode SCCERR_OUTPUTFILE = new ExportStatusCode( 0x63C );
	public static final ExportStatusCode SCCERR_TRUNCATIONLIMITREACHED = new ExportStatusCode( 0x640 );
	public static final ExportStatusCode SCCERR_NONBREAKINGREPEAT = new ExportStatusCode( 0x641 );
	public static final ExportStatusCode SCCERR_NONBREAKINGTEMPLATE = new ExportStatusCode( 0x642 );
	public static final ExportStatusCode SCCERR_INVALIDATTRIBUTE = new ExportStatusCode( 0x643 );
	public static final ExportStatusCode SCCERR_INVALIDATTRIBVALUE = new ExportStatusCode( 0x644 );
	public static final ExportStatusCode SCCERR_MALFORMEDUNIT = new ExportStatusCode( 0x645 );
	public static final ExportStatusCode SCCERR_TEXTBUFFERTOOSMALL = new ExportStatusCode( 0x646 );
	public static final ExportStatusCode SCCERR_BUFFERTOOSMALLFORGRAPHICS = new ExportStatusCode( 0x647 );
	public static final ExportStatusCode SCCERR_INTERNALEXMU = new ExportStatusCode( 0x648 );
	public static final ExportStatusCode SCCERR_INTERNALEXLM = new ExportStatusCode( 0x649 );
	public static final ExportStatusCode SCCERR_INTERNALPARA = new ExportStatusCode( 0x64A );
	public static final ExportStatusCode SCCERR_INTERNALSTYLE = new ExportStatusCode( 0x64B );
	public static final ExportStatusCode SCCERR_INTERNALTABLE = new ExportStatusCode( 0x64C );
	public static final ExportStatusCode SCCERR_INTERNALTAGS  = new ExportStatusCode( 0x64D );
	public static final ExportStatusCode SCCERR_INTERNALGRAPHICS = new ExportStatusCode( 0x64E );
	public static final ExportStatusCode SCCERR_GRIDCELLLIMITREACHED = new ExportStatusCode( 0x64F );
	public static final ExportStatusCode SCCERR_BI_LASTERROR = new ExportStatusCode( 0x64F );

	public static final ExportStatusCode SCCERR_STARTPAGEERROR = new ExportStatusCode( 0x700 );
	public static final ExportStatusCode SCCERR_ENDPAGEERROR = new ExportStatusCode( 0x701 );

	public static final ExportStatusCode SCCERR_JAVA_INTERRUPTED = new ExportStatusCode( 0x800 );
	public static final ExportStatusCode SCCERR_JAVA_IO_ERROR = new ExportStatusCode( 0x801 );
	public static final ExportStatusCode SCCERR_JAVA_TIMEDOUT = new ExportStatusCode( 0x802 );
	public static final ExportStatusCode SCCERR_JAVA_SEGVIOLATION = new ExportStatusCode(0xc1);



	private int code;

	/**
	 * The default constructor is private to prevent creation of an <code>ExportStatusCode</code> without
	 * providing a code value.
	 */
	@SuppressWarnings("unused")
	private ExportStatusCode() {}

	/**
	 * Construct an <code>ExportStatusCode</code> object using the provided integer code value.
	 *
	 * @param code   The conversion return code to be wrapped.
	 */
	public ExportStatusCode( int code ) {
		this.code = code;
	}

	/**
	 * Gets the <code>ExportStatusCode</code> code value.
	 *
	 * @return The integer value of this <code>ExportStatusCode</code>.
	 */
	public int getCode() {
		return code;
	}

	/**
	 * Gets the text representation of the <code>ExportStatusCode</code> using the default <code>Locale</code>.
	 *
	 * @return A <code>String</code> containing the text for this <code>ExportStatusCode</code>.
	 */
	public String getCodeText() {
		ResourceBundle resource = ResourceBundle.getBundle( ExportResources.class.getName() );
		return resource.getString( Integer.toString( code ) );
	}

	/**
	 * Gets the text representation of the <code>ExportStatusCode</code> using the provided <code>Locale</code>.
	 *
	 * @param locale The <code>Locale</code> to use when obtaining the <code>ExportStatusCode</code> text.
	 * @return A <code>String</code> containing the text for this <code>ExportStatusCode</code>.
	 */
	public String getCodeText( Locale locale ) {
		ResourceBundle resource = ResourceBundle.getBundle( ExportResources.class.getName(), locale );
		return resource.getString( Integer.toString( code ) );
	}

	/**
	 * Gets the text representation of the <code>ExportStatusCode</code> in the same way as
	 * {@link #getCodeText() getCodeText} does.
	 *
	 * @return A <code>String</code> containing the text for this <code>ExportStatusCode</code>
	 */
	public String toString() {
		return getCodeText();
	}

	/**
	 * Determines if two <code>ExportCodeText</code> instances are equal, by testing the equality of their integer
	 * values.
	 *
	 * @param obj    The <code>ExportStatusCode</code> to test for equality with.
	 * @return A boolean representing the results of the equality test.
	 */
	public boolean equals( Object obj ) {
		if ( obj == null )
			return false;

		if ( ( ( ExportStatusCode )obj ).getCode() == code )
			return true;

		return false;
	}
}
